# These are supported funding model platforms

github: [ltp, crf, lucthienphong]
patreon: lucthienphong
open_collective: lucthienphong
ko_fi: lucthienphong
tidelift: gcc/g++
community_bridge: stdsys.h
liberapay: lucthienphong
issuehunt: lucthienphong
otechie: lucthienphong
custom: https://me.momo.vn/ltp1120
